swagger: "2.0"
info:
  description: "The project involves the conception and implementation of an online\
    \ presence of the Adult Education Center Langquaid eV (VHS LQ), which has been\
    \ specially optimized for mobile devices. This is referred to below as an app.\
    \ The app should enable the user to view, book and unsubscribe from courses. In\
    \ addition, he should be shown a map for the individual seminar rooms."
  version: "1.0.0"
  title: "VHS\_Langquaid Mobile\_App"
  contact:
    email: "markus.guder@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "prod-ps-ss18-vhslanquaid.herokuapp.com"
basePath: "/v1"
paths:
  /user:
    get:
      tags:
      - "User"
      summary: "get me"
      description: "Get authorized User (me)"
      operationId: "userGET"
      responses:
        200:
          description: "get user"
          schema:
            $ref: "#/definitions/User"
        401:
          description: Invalid authentication credentials.
        403:
          description: Permission 'xxx' denied on file 'yyy'. 
        404:
          description: The specified resource was not found
        409:
          description: Resource 'xxx' already exists.
        500:
          description: Internal Server Error.
      security:
      - JWT: []
      x-swagger-router-controller: "User"
    post:
      tags:
      - "User"
      summary: "register a new user"
      description: "register new user"
      operationId: "userPOST"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      - "application/xml"
      parameters:
      - in: "body"
        name: "data"
        description: "user data"
        required: true
        schema:
          type: "object"
      responses:
        201:
          description: "user created"
          schema:
            type: "object"
            properties: {}
        401:
          description: Invalid authentication credentials.
        403:
          description: Permission 'xxx' denied on file 'yyy'.  
        404:
          description: Permission 'xxx' denied on file 'yyy'.
        409:
          description: Resource 'xxx' already exists.
        500:
          description: Internal Server Error.
      security:
      - JWT: []
      x-swagger-router-controller: "User"
  /user/{user_id}:
    put:
      tags:
      - "User"
      summary: "edit user details"
      operationId: "userUser_idPUT"
      parameters:
      - name: "user_id"
        in: "path"
        required: true
        type: "integer"
      responses:
        200:
          description: "user has been edited"
          schema:
            type: "object"
            properties: {}
        401:
          description: Invalid authentication credentials.
        403:
          description: Permission 'xxx' denied on file 'yyy'.  
        404:
          description: Permission 'xxx' denied on file 'yyy'.
        409:
          description: Resource 'xxx' already exists.
        500:
          description: Internal Server Error.
      security:
      - JWT: []
      x-swagger-router-controller: "User"
  /categories:
    get:
      tags:
      - "Categories"
      summary: "get all categories"
      description: "get all categories"
      operationId: "categoriesGET"
      parameters: []
      responses:
        200:
          description: "request successful"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Category"
        401:
          description: Invalid authentication credentials.
        403:
          description: Permission 'xxx' denied on file 'yyy'.  
        404:
          description: Permission 'xxx' denied on file 'yyy'.
        409:
          description: Resource 'xxx' already exists.
        500:
          description: Internal Server Error.
      security:
      - PublicKey: []
      x-swagger-router-controller: "Categories"
  /categories/{category_id}:
    get:
      tags:
      - "Categories"
      summary: "get category by id"
      description: "get category by id"
      operationId: "categoriesCategory_idGET"
      parameters:
      - name: "category_id"
        in: "path"
        required: true
        type: "integer"
      responses:
        200:
          description: "request successful"
          schema:
            $ref: "#/definitions/Category"
        401:
          description: Invalid authentication credentials.
        403:
          description: Permission 'xxx' denied on file 'yyy'.  
        404:
          description: Permission 'xxx' denied on file 'yyy'.
        409:
          description: Resource 'xxx' already exists.
        500:
          description: Internal Server Error.
      security:
      - PublicKey: []
      x-swagger-router-controller: "Categories"
  /categories/{category_id}/courses:
    get:
      tags:
      - "Categories"
      summary: "get all courses of a category"
      description: "get all courses of a category"
      operationId: "categoriesCategory_idCoursesGET"
      parameters:
      - name: "category_id"
        in: "path"
        required: true
        type: "integer"
      responses:
        200:
          description: "request successful"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Course"
        401:
          description: Invalid authentication credentials.
        403:
          description: Permission 'xxx' denied on file 'yyy'.  
        404:
          description: Permission 'xxx' denied on file 'yyy'.
        409:
          description: Resource 'xxx' already exists.
        500:
          description: Internal Server Error.
      security:
      - PublicKey: []
      x-swagger-router-controller: "Categories"
  /courses:
    get:
      tags:
      - "Courses"
      summary: "get all courses"
      description: "get all courses"
      operationId: "coursesGET"
      parameters: []
      responses:
        200:
          description: "request successful"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Course"
        401:
          description: Invalid authentication credentials.
        403:
          description: Permission 'xxx' denied on file 'yyy'.  
        404:
          description: Permission 'xxx' denied on file 'yyy'.
        409:
          description: Resource 'xxx' already exists.
        500:
          description: Internal Server Error.
      security:
      - PublicKey: []
      x-swagger-router-controller: "Courses"
  /courses/{course_id}:
    get:
      tags:
      - "Courses"
      summary: "get course by id"
      description: "get course by id"
      operationId: "coursesCourse_idGET"
      parameters:
      - name: "course_id"
        in: "path"
        required: true
        type: "integer"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Course"
        401:
          description: Invalid authentication credentials.
        403:
          description: Permission 'xxx' denied on file 'yyy'.  
        404:
          description: Permission 'xxx' denied on file 'yyy'.
        409:
          description: Resource 'xxx' already exists.
        500:
          description: Internal Server Error.
      security:
      - PublicKey: []
      x-swagger-router-controller: "Courses"
  /courses/highlights:
    get:
      tags:
      - "Courses"
      summary: "get currated highlights"
      description: "get currated highlights"
      operationId: "coursesHighlightsGET"
      parameters: []
      responses:
        200:
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Course"
        401:
          description: Invalid authentication credentials.
        403:
          description: Permission 'xxx' denied on file 'yyy'.  
        404:
          description: Permission 'xxx' denied on file 'yyy'.
        409:
          description: Resource 'xxx' already exists.
        500:
          description: Internal Server Error.
      security:
      - PublicKey: []
      x-swagger-router-controller: "Courses"
  /courses/{course_id}/apply:
    post:
      tags:
      - "Courses"
      summary: "apply to participate in specific course"
      description: "apply to participate in specific course"
      operationId: "coursesCourse_idApplyPOST"
      parameters:
      - name: "course_id"
        in: "path"
        required: true
        type: "integer"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Course"
        401:
          description: Invalid authentication credentials.
        403:
          description: Permission 'xxx' denied on file 'yyy'.  
        404:
          description: Permission 'xxx' denied on file 'yyy'.
        409:
          description: Resource 'xxx' already exists.
        500:
          description: Internal Server Error.
      security:
      - JWT: []
      x-swagger-router-controller: "Courses"
  /courses/{course_id}/signoff:
    post:
      tags:
      - "Courses"
      summary: "signoff to participate in specific course"
      description: "signoff to participate in specific course"
      operationId: "coursesCourse_idSignoffPOST"
      parameters:
      - name: "course_id"
        in: "path"
        required: true
        type: "integer"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Course"
        401:
          description: Invalid authentication credentials.
        403:
          description: Permission 'xxx' denied on file 'yyy'.  
        404:
          description: Permission 'xxx' denied on file 'yyy'.
        409:
          description: Resource 'xxx' already exists.
        500:
          description: Internal Server Error.
      security:
      - JWT: []
      x-swagger-router-controller: "Courses"
  /courses/{course_id}/feedback:
    post:
      tags:
      - "Courses"
      summary: "give feedback to a course"
      description: "give feedback to a course"
      operationId: "coursesCourse_idFeedbackPOST"
      parameters:
      - in: "body"
        name: "data"
        required: false
        schema:
          $ref: "#/definitions/CourseFeedback"
      - name: "course_id"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/CourseFeedback"
        401:
          description: Invalid authentication credentials.
        403:
          description: Permission 'xxx' denied on file 'yyy'.  
        404:
          description: Permission 'xxx' denied on file 'yyy'.
        409:
          description: Resource 'xxx' already exists.
        500:
          description: Internal Server Error.
      security:
      - JWT: []
      x-swagger-router-controller: "Courses"
  /contact:
    post:
      tags:
      - "Contact"
      summary: "give general feedback to the team"
      description: "give general feedback to the team"
      operationId: "contactPOST"
      parameters:
      - in: "body"
        name: "data"
        required: true
        schema:
          $ref: "#/definitions/GeneralFeedback"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/GeneralFeedback"
        401:
          description: Invalid authentication credentials.
        403:
          description: Permission 'xxx' denied on file 'yyy'.  
        404:
          description: Permission 'xxx' denied on file 'yyy'.
        409:
          description: Resource 'xxx' already exists.
        500:
          description: Internal Server Error.
      security:
      - PublicKey: []
      x-swagger-router-controller: "Contact"
  /auth:
    post:
      tags:
      - "Auth"
      summary: "get authtoken from server"
      description: "get authtoken from server"
      operationId: "authPOST"
      parameters:
      - in: "body"
        name: "data"
        required: true
        schema:
          $ref: "#/definitions/UserData"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/AuthData"
      security:
      - PublicKey: []
      x-swagger-router-controller: "Auth"
securityDefinitions:
  PublicKey:
    type: "apiKey"
    name: "Authorization"
    in: "header"
  JWT:
    type: "apiKey"
    name: "Authorization"
    in: "header"
definitions:
  Category:
    type: "object"
    required:
    - "id"
    properties:
      id:
        type: "integer"
        example: 1
        description: "the category ID"
      name:
        type: "string"
        example: "Kunst"
        description: "the category name"
      text:
        type: "string"
        example: "Kunst ist toll"
        description: "the category description"
    example:
      name: "Kunst"
      id: 1
      text: "Kunst ist toll"
  Course:
    type: "object"
    required:
    - "id"
    properties:
      id:
        type: "integer"
        example: 1
        description: "the course id"
      name:
        type: "string"
        example: "Kunst-Grundkurs"
        description: "the course name"
      text:
        type: "string"
        example: "Dass Kunst nicht immer fad ist, soll in diesem Kurs klar gemacht\
          \ werden"
        description: "the course description"
      min_age:
        type: "integer"
        example: 1
        description: "minimum required age to participate"
      max_age:
        type: "integer"
        example: 99
        description: "maximum required age to participate"
    example:
      max_age: 99
      name: "Kunst-Grundkurs"
      id: 1
      text: "Dass Kunst nicht immer fad ist, soll in diesem Kurs klar gemacht werden"
      min_age: 1
  User:
    type: "object"
    required:
    - "id"
    properties:
      id:
        type: "integer"
        example: 1
        description: "the user ID"
      firstname:
        type: "string"
        example: "Hans"
        description: "the users firstname"
      lastname:
        type: "string"
        example: "Schuller"
        description: "the users firstname"
      email:
        type: "string"
        example: "email@internet.com"
        description: "the users email adress"
      password:
        type: "string"
        example: "hunter22"
        description: "the users password"
    example:
      firstname: "Hans"
      password: "hunter22"
      id: 1
      email: "email@internet.com"
      lastname: "Schuller"
  GeneralFeedback:
    type: "object"
    required:
    - "text"
    properties:
      text:
        type: "string"
        example: "This app is great!"
        description: "the content of the message"
      email:
        type: "string"
        example: "this@me.com"
        description: "the optional email adress"
    example:
      text: "This app is great!"
      email: "this@me.com"
  CourseFeedback:
    type: "object"
    required:
    - "text"
    properties:
      text:
        type: "string"
        example: "This app is great!"
        description: "the content of the message"
      email:
        type: "string"
        example: "this@me.com"
        description: "the optional email adress"
    example:
      text: "This app is great!"
      email: "this@me.com"
  UserData:
    type: "object"
    required:
    - "email"
    - "password"
    properties:
      email:
        type: "string"
        example: "user123@email.com"
      password:
        type: "string"
        example: "hunter22"
    example:
      password: "hunter22"
      email: "user123@email.com"
    xml:
      name: "UserData"
  AuthData:
    type: "object"
    required:
    - "token"
    properties:
      token:
        type: "string"
        example: "abc.123321.cba"
    example:
      token: "abc.123321.cba"
  
      # Schema for error response body
      Error:
        type: object
        properties:
          code:
            type: string
          message:
            type: string
        required:
          - code
          - message  